name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project (if needed)
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ruchika1915/codeweave:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ruchika1915/codeweave:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull ruchika1915/codeweave:latest

      - name: Remove old container (if exists)
        run: docker rm -f nodejs-app-container || true

      - name: Run New Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app-container \
            ruchika1915/codeweave:latest
